services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: ${NGINX_CONTAINER}
    restart: unless-stopped
    ports:
      - '${PORTS_HTTP}'      # Porta HTTP
      - '${PORTS_HTTPS}'    # Porta HTTPS
      - '${PORTS_WEB}'      # Interface Web
    environment:
      DB_MYSQL_HOST: "${DB_MYSQL_HOST}"  # Usando seu MySQL existente
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: "${DB_MYSQL_USER}"
      DB_MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD}"
      DB_MYSQL_NAME: "${DB_MYSQL_NAME}"
    volumes:
      - ${VOL_NGINX_DATA}
      - ${VOL_NGINX_LETSENCRYPT}
      - ${VOL_TZ}
      - ${VOL_LOCALTIME}
    networks:
      network-share:
        ipv4_address: ${IPV4_NGINX}
networks:
  network-share:
    external: true
    ipam:
      config:
        - subnet: ${SUBNET}
